[pytest]
addopts = -v --tb=short --html=./reports/report.html --self-contained-html
testpaths = ./scripts
python_files = test*.py
python_classes = Test*
python_functions = test_*
markers =
    mp: 自媒体模块测试
    mis: 后台管理模块测试
    app: APP模块测试
